### ISSUE TITLE
BoringSSL-GRPC error

### ISSUE THREAD

**Issue by iOS-jeb** [oblivioned/xuper-sdk-oc#1]
pod卡在那就不动了，出师未捷啊，能否手动导入，能否加下您微信。

**Comment by oblivioned** [comment]
要记得使用科学上网，记得在 pod install 的时候增加 --verbose 选项查看进度。。

grpc的库特别大，而且国内连接github的速度也很慢导致的。

**Comment by oblivioned** [comment]
微信的话，你可以私信我留下您的微信号，我这边看到了会添加，或者到官方2群，不二心。

另外有什么不明白的，都可以和我讨论，这套sdk实现的很仓储，很多地方结构不是太好。都是因为最开始的时候没想清楚。

所以我会尽量的辅助使用者。
